/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./App.{js,jsx}",
    "./app/**/*.{js,jsx}",
    "./screens/**/*.{js,jsx}",
    "./components/**/*.{js,jsx}",
    "./navigation/**/*.{js,jsx}",
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        primary: "#ff7700",
        "brand-red": "#F83B0A",
        "primary-dark": "#ce2d04",
        "primary-light": "#fff5ec",
        "price-red": "#f83b0a",
        "brand-blue": "#2878ff",
        "brand-blue-light": "#eef4ff",
        success: "#37a446",
        "success-light": "#dbf4e5",
        "discount-green": "#2a9d4e",
        "discount-blue": "#1a7fd4",
        "discount-blue-light": "#e0f0ff",
        "text-primary": "#212529",
        "text-secondary": "#6c757d",
        "text-muted": "#adb5bd",
        placeholder: "#818181",
        "text-subtle": "#888888",
        "bg-light": "#f5f5f5",
        "bg-faint": "#fafafa",
        "border-light": "#dddddd",
        "border-input": "#BDBDBD",
        "border-subtle": "#f0f0f0",
        "border-second-subtle": "#BDBDBD",
        badge: "#ff4d2d",
        "fav-red": "#e84040",
        "fav-red-light": "#fff0f0",
      },
      borderRadius: {
        xs: "4px",
        sm: "6px",
        DEFAULT: "8px",
        md: "10px",
        lg: "12px",
        xl: "20px",
        full: "999px",
      },
      fontSize: {
        "2xs": ["10px", { lineHeight: "14px" }],
        xs: ["11px", { lineHeight: "16px" }],
        sm: ["12px", { lineHeight: "18px" }],
        base: ["13px", { lineHeight: "20px" }],
        md: ["14px", { lineHeight: "20px" }],
        lg: ["16px", { lineHeight: "24px" }],
        xl: ["18px", { lineHeight: "26px" }],
        "2xl": ["22px", { lineHeight: "30px" }],
        "3xl": ["28px", { lineHeight: "36px" }],
      },
      fontFamily: {
        sans: ["Inter_400Regular", "System"],
        "sans-medium": ["Inter_500Medium", "System"],
        "sans-semibold": ["Inter_600SemiBold", "System"],
        "sans-bold": ["Inter_700Bold", "System"],
        "sans-extrabold": ["Inter_800ExtraBold", "System"],
      },
    },
  },
  plugins: [],
};
